//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PSS_Project_Category
    {
        public PSS_Project_Category()
        {
            this.PSS_Projects = new HashSet<PSS_Projects>();
        }
        
        public int proj_category_id { get; set; }
        [Required(ErrorMessage = "Please enter Project Category")]
        public string category { get; set; }
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<PSS_Projects> PSS_Projects { get; set; }
    }
}
