//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PSS_Users
    {
        public PSS_Users()
        {
            this.PSS_Projects = new HashSet<PSS_Projects>();
            this.PSS_Student_Project = new HashSet<PSS_Student_Project>();
        }
    
        public int user_id { get; set; }
        
        [StringLength(50)]
        [Required(ErrorMessage = "Please enter First Name")]
        [Display(Description = "First Name")]
        [RegularExpression("([a-zA-Z .&'-]+)", ErrorMessage = "Please enter a valid name")]
        public string first_name { get; set; }
        
        [StringLength(50)]
        [Required(ErrorMessage = "Please enter Last Name")]
        [Display(Description = "Last Name")]
        [RegularExpression("([a-zA-Z .&'-]+)", ErrorMessage = "Please enter a valid name")]
        public string last_name { get; set; }
        
        [Required(ErrorMessage = "Please enter email")]
        [Display(Description = "Email")]
        [RegularExpression(@"(\w+@[murraystate]+?\.[edu]{3})", ErrorMessage = "Please enter your Murray State email id")]
        public string email { get; set; }

        [StringLength(10)]
        [RegularExpression("([0-9 .&'-]+)", ErrorMessage = "Please enter a valid name")]
        public string contact { get; set; }

        [Required]
        public Nullable<int> user_type_id { get; set; }
        
        public Nullable<bool> active { get; set; }
    
        public virtual ICollection<PSS_Projects> PSS_Projects { get; set; }
        public virtual PSS_User_Type PSS_User_Type { get; set; }
        public virtual ICollection<PSS_Student_Project> PSS_Student_Project { get; set; }
    }
}
