//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    
    public partial class PSS_Projects
    {
        public PSS_Projects()
        {
            this.PSS_Student_Project = new HashSet<PSS_Student_Project>();
        }
    
        public int project_id { get; set; }
        [Required(ErrorMessage = "Please enter Project Title")]
        public string project_title { get; set; }
        [Required(ErrorMessage = "Please enter Project Description")]
        public string description { get; set; }
        public Nullable<int> proj_category_id { get; set; }
        public Nullable<int> project_status_id { get; set; }
        public string extra_details { get; set; }
        public Nullable<int> sponsor_id { get; set; }
        public string material_budget { get; set; }
        public string preferred_major { get; set; }
        public Nullable<int> user_id { get; set; }
        public Nullable<System.DateTime> project_created_date { get; set; }
        public Nullable<System.DateTime> project_selection_closing_date { get; set; }
        public Nullable<bool> active { get; set; }
        public HttpPostedFileBase documentData { get; set; }
    
        public virtual PSS_Project_Category PSS_Project_Category { get; set; }
        public virtual PSS_Sponsor PSS_Sponsor { get; set; }
        public virtual PSS_Status PSS_Status { get; set; }
        public virtual PSS_Users PSS_Users { get; set; }
        public virtual ICollection<PSS_Student_Project> PSS_Student_Project { get; set; }
    }
}
