//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSS.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class PSS_Student_Project
    {
        public int project_request_id { get; set; }
        public Nullable<int> student_id { get; set; }
        public int project_id { get; set; }
        public Nullable<System.DateTime> requested_date { get; set; }
        public int project_request_status_id { get; set; }
        public byte[] document { get; set; }
        public string file_name { get; set; }
        public HttpPostedFileBase documentData { get; set; }
    
        public virtual PSS_Projects PSS_Projects { get; set; }
        public virtual PSS_Status PSS_Status { get; set; }
        public virtual PSS_Users PSS_Users { get; set; }
    }
}
